name: CI/CD - Python FastAPI Docker & Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4


      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_ID }}
          export_default_credentials: true

      - name: Activate service account
        run: |
          echo '${{ secrets.GCP_KEY }}' > key.json
          gcloud auth activate-service-account ${{ secrets.GCP_EMAIL }} --key-file=key.json

      - name: Set active account
        run: |
          gcloud config set account ${{ secrets.GCP_EMAIL }}

      - name: SSH into VM and run deployment script
        run: |
          gcloud compute ssh mapharu00@haru-server \
            --zone=asia-northeast3-c \
            --tunnel-through-iap \
            --command="cd /home/mapharu00/haru-fastapi && bash run.sh"
