name: CI/CD - Python FastAPI Docker & Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: parkjunhyeon/haru-fastapi:${{ github.sha }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_ID }}

      - name: Upload .env file to VM (if needed)
        run: |
          gcloud compute ssh haru-server \
          --zone=asia-northeast3-c \
          --tunnel-through-iap \
          --command="echo '${{ secrets.FASTAPI_ENV }}' > /fastapi.env"

      - name: Deploy to GCP VM via IAP
        run: |
          gcloud compute ssh haru-server \
          --zone=asia-northeast3-c \
          --tunnel-through-iap \
          --command="docker pull parkjunhyeon/haru-fastapi:${{ github.sha }} && \
                     docker stop haru-fastapi || true && \
                     docker rm haru-fastapi || true && \
                     docker run -d -p 8000:8000 \
                       --name haru-fastapi \
                       -e TZ=Asia/Seoul \
                       --env-file /fastapi.env \
                       parkjunhyeon/haru-fastapi:${{ github.sha }}"
